"""
SysML v2 Model Validator via Jupyter Kernel

Programmatically drives the SysML v2 Jupyter kernel to load, validate, and
visualize a SysML v2 model. Produces a structured JSON report, standalone SVG
diagram files, and a reviewable .ipynb notebook with all outputs embedded.

The script executes raw SysML code in the kernel to register elements in the
namespace (enabling %show and %viz). If raw execution fails, it falls back to
%publish for syntax validation. Visualization uses %viz with --view flags.

Prerequisites:
    - Java 17+ (JAVA_HOME must be set)
    - jupyter-sysml-kernel (conda install -c conda-forge jupyter-sysml-kernel)
    - jupyter_client, nbformat (pip install jupyter_client nbformat)

Usage:
    python scripts/validate_model.py
    python scripts/validate_model.py --dry-run
    python scripts/validate_model.py --repo-path . --output-dir scripts/output
    python scripts/validate_model.py --viz-elements SaturnV,Apollo11Mission
    python scripts/validate_model.py --no-continue-on-error

Author:
    Generated by Antigravity AI assistant

Copyright:
    (c) 2026. Licensed under the terms specified in LICENSE.md
"""

import os
import re
import sys
import json
import time
import logging
import argparse
import pathlib
from dataclasses import dataclass, field, asdict
from typing import List, Dict, Tuple, Optional, Any
from collections import defaultdict

# ---------------------------------------------------------------------------
# Logging setup
# ---------------------------------------------------------------------------
logger = logging.getLogger("sysml_validator")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
SYSML_V2_STANDARD_LIBRARIES = frozenset([
    "NumericalFunctions", "ScalarFunctions", "CollectionFunctions",
    "ControlFunctions", "Metaobjects", "States", "Parts",
    "OccurrenceFunctions", "ISQ", "SI", "USCustomaryUnits",
    "MeasurementReferences", "Quantities", "ScalarValues", "Time",
    "ModelingMetadata", "ShapeItems", "Base", "Occurrences",
    "Objects", "Items", "Connections", "Ports", "Actions",
    "Calculations", "Constraints", "Requirements", "Cases",
    "AnalysisCases", "VerificationCases", "UseCases", "Views",
    "Allocations", "Interfaces", "Metadata", "KerML",
    "RatioScale", "RatioValue", "SysML",
])

# Default visualization targets: list of (package_name, view_type) tuples.
# The %viz command syntax is: %viz <PackageName> --view <ViewType>
# NOTE: %viz operates at the PACKAGE level, not on individual part defs.
# Common view types: tree, interconnection, Action, State
DEFAULT_VIZ_ELEMENTS = [
    ("TechnicalComponentsPackage", "tree"),
    ("MissionPackage", "tree"),
    ("SystemPackage", "interconnection"),
    ("FunctionsPackage", "tree"),
]

KERNEL_NAME = "sysml"


def _to_kernel_path(file_path: str) -> str:
    """
    Convert a Windows file path to a forward-slash path for the SysML kernel.
    The kernel runs on Java, which works best with forward slashes.
    """
    return pathlib.PureWindowsPath(os.path.abspath(file_path)).as_posix()

# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class FileResult:
    """Result of validating a single .sysml file."""
    package_name: str
    file_path: str
    status: str = "pending"        # "pass", "fail", "error", "skipped"
    load_method: str = ""           # "publish", "raw", or "" if not attempted
    errors: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    stdout_output: List[str] = field(default_factory=list)
    show_output: List[str] = field(default_factory=list)
    execution_time_s: float = 0.0

@dataclass
class VizResult:
    """Result of a %viz command."""
    element_name: str
    view_type: str = "tree"
    status: str = "pending"        # "pass", "fail", "error"
    svg_path: Optional[str] = None
    html_path: Optional[str] = None
    pdf_path: Optional[str] = None
    png_path: Optional[str] = None
    errors: List[str] = field(default_factory=list)
    package_name: Optional[str] = None


@dataclass
class ValidationReport:
    """Full validation report for the model."""
    timestamp: str = ""
    repo_path: str = ""
    total_files: int = 0
    passed: int = 0
    failed: int = 0
    errors: int = 0
    skipped: int = 0
    total_time_s: float = 0.0
    file_results: List[FileResult] = field(default_factory=list)
    viz_results: List[VizResult] = field(default_factory=list)
    loading_order: List[str] = field(default_factory=list)


# ===========================================================================
# Dependency Resolution
# ===========================================================================

class SysMLDependencyResolver:
    """
    Resolves the loading order for .sysml files by parsing import statements
    and performing a topological sort of the dependency graph.
    """

    IMPORT_PATTERN = re.compile(
        r'(?:private\s+)?import\s+([\w]+)(?:::[\w*]+)*'
    )
    # Matches: PackageName::ElementName (inline references)
    INLINE_PATTERN = re.compile(
        r'\b([\w]+)::'
    )

    def __init__(self, repo_path: str):
        self.repo_path = os.path.abspath(repo_path)
        self.package_index: Dict[str, str] = {}  # package_name -> relative_path
        self.dep_graph: Dict[str, set] = defaultdict(set)
        self._load_meta_index()

    def _load_meta_index(self) -> None:
        """Load the package-to-file index from .meta.json."""
        meta_path = os.path.join(self.repo_path, ".meta.json")
        if os.path.isfile(meta_path):
            with open(meta_path, "r", encoding="utf-8") as f:
                meta = json.load(f)
            self.package_index = dict(meta.get("index", {}))
            logger.info(
                "Loaded %d packages from .meta.json", len(self.package_index)
            )
        else:
            logger.warning(
                ".meta.json not found at %s — falling back to file discovery",
                meta_path,
            )
            self._discover_packages()

    def _discover_packages(self) -> None:
        """Fallback: discover packages by walking the directory tree."""
        for root, _, files in os.walk(self.repo_path):
            for fname in files:
                if fname.endswith(".sysml"):
                    pkg_name = fname.replace(".sysml", "")
                    rel_path = os.path.relpath(
                        os.path.join(root, fname), self.repo_path
                    )
                    self.package_index[pkg_name] = rel_path

    def get_imports(self, file_path: str) -> List[str]:
        """Extract import package names from a .sysml file."""
        if not os.path.isfile(file_path):
            return []
        try:
            with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read()
            
            # Find explicit imports
            matches = self.IMPORT_PATTERN.findall(content)
            
            # Also find inline namespace references (e.g. CapabilitiesPackage::Element)
            inline_matches = self.INLINE_PATTERN.findall(content)
            
            # Deduplicate while preserving order
            seen = set()
            unique = []
            for m in matches + inline_matches:
                if m not in seen:
                    seen.add(m)
                    unique.append(m)
            return unique
        except IOError as e:
            logger.error("Error reading %s: %s", file_path, e)
            return []

    def build_dependency_graph(self) -> None:
        """Build the directed dependency graph from all indexed packages."""
        for pkg_name, rel_path in self.package_index.items():
            abs_path = os.path.join(self.repo_path, rel_path)
            imports = self.get_imports(abs_path)
            project_deps = set()
            for imp in imports:
                if imp in self.package_index and imp != pkg_name:
                    project_deps.add(imp)
                elif imp not in SYSML_V2_STANDARD_LIBRARIES:
                    logger.debug(
                        "Package '%s' imports unknown '%s' (may be stdlib)",
                        pkg_name, imp,
                    )
            self.dep_graph[pkg_name] = project_deps
            # Ensure all nodes exist even if they have no deps
            for dep in project_deps:
                if dep not in self.dep_graph:
                    self.dep_graph[dep] = set()

    def topological_sort(self) -> List[str]:
        """
        Perform a topological sort (Kahn's algorithm) on the dependency graph.
        Returns packages in loading order (dependencies first).
        """
        # Compute in-degree for each node
        in_degree: Dict[str, int] = {
            node: 0 for node in self.dep_graph
        }
        for node, deps in self.dep_graph.items():
            for dep in deps:
                in_degree[node] = in_degree.get(node, 0)
                # dep is a dependency OF node, meaning node depends on dep
                # So we don't increment dep's in-degree here

        # Recalculate: in_degree[X] = number of packages that X depends on?
        # No — in_degree[X] = number of edges pointing INTO X
        # An edge from A to B means "A depends on B", so B must load first.
        # That means B has an incoming edge from A in the "depends on" graph.
        # But for topological sort, we want to reverse: B should come before A.
        # So we build a "dependency-of" (reverse) graph.

        # Reverse the graph: if A depends on B, add edge B -> A
        reverse_graph: Dict[str, set] = defaultdict(set)
        in_degree_correct: Dict[str, int] = {
            node: 0 for node in self.dep_graph
        }
        for node, deps in self.dep_graph.items():
            in_degree_correct[node] = len(deps)
            for dep in deps:
                reverse_graph[dep].add(node)
                if dep not in in_degree_correct:
                    in_degree_correct[dep] = 0

        # Kahn's algorithm
        queue = [
            node for node, deg in in_degree_correct.items() if deg == 0
        ]
        queue.sort()  # deterministic ordering for same-depth nodes
        result = []

        while queue:
            node = queue.pop(0)
            result.append(node)
            for neighbor in sorted(reverse_graph.get(node, set())):
                in_degree_correct[neighbor] -= 1
                if in_degree_correct[neighbor] == 0:
                    queue.append(neighbor)

        if len(result) != len(self.dep_graph):
            missing = set(self.dep_graph.keys()) - set(result)
            logger.error(
                "Circular dependency detected! Could not sort: %s", missing
            )
            # Append remaining in arbitrary order
            for m in sorted(missing):
                result.append(m)

        return result

    def resolve(self) -> List[Tuple[str, str]]:
        """
        Build the graph and return an ordered list of (package_name, abs_path)
        tuples ready for loading into the kernel.
        """
        self.build_dependency_graph()
        order = self.topological_sort()

        result = []
        for pkg_name in order:
            if pkg_name in self.package_index:
                abs_path = os.path.join(
                    self.repo_path, self.package_index[pkg_name]
                )
                result.append((pkg_name, abs_path))
            else:
                logger.warning(
                    "Package '%s' is in the graph but has no file mapping",
                    pkg_name,
                )
        return result


# ===========================================================================
# Kernel Validator
# ===========================================================================

class SysMLKernelValidator:
    """
    Drives the SysML v2 Jupyter kernel via jupyter_client to validate
    .sysml files and capture visualization output.
    """

    def __init__(
        self,
        timeout: int = 60,
        startup_timeout: int = 120,
    ):
        self.timeout = timeout
        self.startup_timeout = startup_timeout
        self.km = None
        self.kc = None

    def start_kernel(self) -> None:
        """Start the SysML v2 Jupyter kernel."""
        try:
            from jupyter_client import KernelManager
        except ImportError:
            raise RuntimeError(
                "jupyter_client is not installed. "
                "Install it with: pip install jupyter_client"
            )

        logger.info("Starting SysML v2 Jupyter kernel...")
        self.km = KernelManager(kernel_name=KERNEL_NAME)

        try:
            self.km.start_kernel()
        except Exception as e:
            raise RuntimeError(
                f"Failed to start the '{KERNEL_NAME}' kernel. "
                f"Is it installed? (conda install -c conda-forge jupyter-sysml-kernel)\n"
                f"Error: {e}"
            )

        self.kc = self.km.client()
        self.kc.start_channels()

        try:
            self.kc.wait_for_ready(timeout=self.startup_timeout)
            logger.info("Kernel is ready.")
        except RuntimeError:
            self.shutdown_kernel()
            raise RuntimeError(
                f"Kernel did not become ready within {self.startup_timeout}s. "
                "Check that Java 17+ is installed and JAVA_HOME is set."
            )

    def shutdown_kernel(self) -> None:
        """Shut down the kernel cleanly."""
        if self.kc:
            self.kc.stop_channels()
        if self.km and self.km.is_alive():
            logger.info("Shutting down kernel...")
            self.km.shutdown_kernel(now=True)
            logger.info("Kernel shut down.")

    def execute_cell(self, code: str) -> Dict[str, Any]:
        """
        Execute a code cell in the kernel and collect all outputs.

        Returns a dict with:
            - "status": "ok" or "error"
            - "errors": list of error messages
            - "warnings": list of stderr messages
            - "stdout": list of stdout messages
            - "display_data": list of display_data payloads (for viz)
            - "execute_result": list of execute_result payloads
        """
        if not self.kc:
            raise RuntimeError("Kernel is not running. Call start_kernel() first.")

        msg_id = self.kc.execute(code)
        result = {
            "status": "ok",
            "errors": [],
            "warnings": [],
            "stdout": [],
            "display_data": [],
            "execute_result": [],
        }

        # Drain IOPub messages until we see the idle status for our execution
        while True:
            try:
                msg = self.kc.get_iopub_msg(timeout=self.timeout)
            except Exception:
                result["status"] = "error"
                result["errors"].append(
                    f"Timeout: no response within {self.timeout}s"
                )
                break

            msg_type = msg.get("msg_type", "")
            parent_id = msg.get("parent_header", {}).get("msg_id", "")
            content = msg.get("content", {})

            # Only process messages that belong to our execution
            if parent_id != msg_id:
                continue

            if msg_type == "error":
                result["status"] = "error"
                ename = content.get("ename", "Unknown")
                evalue = content.get("evalue", "")
                traceback_lines = content.get("traceback", [])
                error_msg = f"{ename}: {evalue}"
                result["errors"].append(error_msg)
                if traceback_lines:
                    result["errors"].extend(traceback_lines)

            elif msg_type == "stream":
                name = content.get("name", "")
                text = content.get("text", "")
                if name == "stderr":
                    result["warnings"].append(text)
                elif name == "stdout":
                    result["stdout"].append(text)
                
                # Check for compiler errors in stream output (common in SysML v2 kernel)
                for line in text.splitlines():
                    stripped = line.strip()
                    if stripped.startswith("ERROR:") or stripped.startswith("Error:"):
                        result["status"] = "error"
                        result["errors"].append(stripped)

            elif msg_type == "display_data":
                result["display_data"].append(content.get("data", {}))

            elif msg_type == "execute_result":
                data = content.get("data", {})
                result["execute_result"].append(data)
                
                # Check for compiler or reference errors in execute result (e.g. from %show)
                if "text/plain" in data:
                    plain_text = data["text/plain"]
                    for line in plain_text.splitlines():
                        stripped = line.strip()
                        if stripped.startswith("ERROR:") or stripped.startswith("Error:"):
                            result["status"] = "error"
                            result["errors"].append(stripped)

            elif msg_type == "status":
                if content.get("execution_state") == "idle":
                    break

        return result

    def publish_file(self, file_path: str) -> Dict[str, Any]:
        """
        Load a .sysml file into the kernel using the %publish magic.
        This registers the file's contents in the kernel's model namespace,
        making its definitions available for import by subsequent files.
        """
        kernel_path = _to_kernel_path(file_path)
        code = f"%publish {kernel_path}"
        logger.debug("Publishing: %s", code)
        return self.execute_cell(code)

    def show_element(self, element_name: str) -> Dict[str, Any]:
        """
        Run %show <element> to verify a package/element exists in the kernel.
        Returns the execute_cell result dict.
        """
        code = f"%show {element_name}"
        logger.debug("Verifying: %s", code)
        return self.execute_cell(code)

    def validate_file(self, package_name: str, file_path: str) -> FileResult:
        """
        Validate a single .sysml file by loading it into the kernel.

        Strategy:
          1. Execute the file's raw code (primary — registers elements in the
             kernel namespace so %viz and %show work)
          2. If raw execution fails, fall back to %publish (syntax check only)
          3. Run %show <PackageName> to verify the package registered
        """
        result = FileResult(
            package_name=package_name,
            file_path=file_path,
        )

        if not os.path.isfile(file_path):
            result.status = "error"
            result.errors.append(f"File not found: {file_path}")
            return result

        start_time = time.time()

        # Read the file content
        try:
            with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                code = f.read()
        except IOError as e:
            result.status = "error"
            result.errors.append(f"Could not read file: {e}")
            result.execution_time_s = round(time.time() - start_time, 3)
            return result

        # --- Step 1: Execute raw code (primary — registers namespace) ---
        cell_result = self.execute_cell(code)
        result.load_method = "raw"

        result.errors = cell_result["errors"]
        result.warnings = cell_result["warnings"]
        result.stdout_output = cell_result["stdout"]

        if cell_result["status"] != "ok" or cell_result["errors"]:
            # --- Fallback: try %publish (syntax validation only) ---
            logger.warning(
                "Raw execution failed for %s, falling back to %%publish",
                package_name,
            )
            publish_result = self.publish_file(file_path)
            result.load_method = "publish"

            if publish_result["status"] == "ok" and not publish_result["errors"]:
                # %publish succeeded — file is syntactically valid but
                # elements won't be in namespace for %viz
                result.errors = []
                result.warnings = publish_result["warnings"] + [
                    "Loaded via %publish (syntax only) — elements not in namespace for %viz"
                ]
                result.stdout_output = publish_result["stdout"]
            else:
                # Both methods failed — keep the original raw execution errors
                result.status = "fail"
                result.execution_time_s = round(time.time() - start_time, 3)
                return result

        # --- Step 2: Verify with %show ---
        show_result = self.show_element(package_name)
        result.show_output = show_result.get("stdout", []) + [
            data.get("text/plain", "")
            for data in show_result.get("execute_result", [])
            if "text/plain" in data
        ]

        if show_result["errors"]:
            # %show failed — element not found in namespace
            show_err_text = "; ".join(show_result["errors"])
            if result.load_method == "publish":
                # Expected — %publish doesn't register namespace
                result.warnings.append(
                    f"%show {package_name} not available (loaded via %publish)"
                )
            else:
                # Unexpected — raw execution should register namespace
                result.warnings.append(
                    f"%show {package_name} returned errors: {show_err_text}"
                )
            logger.debug(
                "%%show %s: %s",
                package_name,
                show_result["errors"][0][:100] if show_result["errors"] else "unknown",
            )

        result.execution_time_s = round(time.time() - start_time, 3)

        if not result.errors:
            result.status = "pass"
        else:
            result.status = "fail"

        return result

    def run_viz(
        self, element_name: str, output_dir: str, view_type: str = "tree",
    ) -> VizResult:
        """Execute %viz for an element and save the output."""
        viz_result = VizResult(element_name=element_name, view_type=view_type)

        code = f"%viz {element_name} --view {view_type}"
        logger.info("Running: %s", code)

        cell_result = self.execute_cell(code)

        # Debug: log all data received so we can see what format viz comes in
        logger.debug(
            "  viz status=%s, errors=%d, display_data=%d, execute_result=%d, stdout=%d",
            cell_result["status"],
            len(cell_result["errors"]),
            len(cell_result["display_data"]),
            len(cell_result["execute_result"]),
            len(cell_result["stdout"]),
        )
        for i, dd in enumerate(cell_result["display_data"]):
            logger.debug("  display_data[%d] keys: %s", i, list(dd.keys()))
            for key, val in dd.items():
                preview = str(val)[:150] if isinstance(val, str) else str(type(val))
                logger.debug("    %s: %s", key, preview)
        for i, er in enumerate(cell_result["execute_result"]):
            logger.debug("  execute_result[%d] keys: %s", i, list(er.keys()))
            for key, val in er.items():
                preview = str(val)[:150] if isinstance(val, str) else str(type(val))
                logger.debug("    %s: %s", key, preview)
        for i, so in enumerate(cell_result["stdout"]):
            logger.debug("  stdout[%d]: %s", i, so[:200])
        for i, w in enumerate(cell_result["warnings"]):
            logger.debug("  stderr[%d]: %s", i, w[:200])

        if cell_result["errors"]:
            viz_result.status = "fail"
            viz_result.errors = cell_result["errors"]
            return viz_result

        # Collect all data payloads from both display_data and execute_result
        all_data_payloads = (
            cell_result["display_data"] + cell_result["execute_result"]
        )

        # Search for visualization output across all MIME types
        saved = False
        for payload in all_data_payloads:
            # Priority 1: SVG (text, directly writable)
            if "image/svg+xml" in payload and not saved:
                svg_content = payload["image/svg+xml"]
                out_path = os.path.join(
                    output_dir, f"viz_{element_name}_{view_type}.svg"
                )
                with open(out_path, "w", encoding="utf-8") as f:
                    f.write(svg_content)
                viz_result.svg_path = out_path
                saved = True
                logger.info("Saved SVG to %s", out_path)

            # Priority 2: HTML
            if "text/html" in payload and not saved:
                html_content = payload["text/html"]
                out_path = os.path.join(
                    output_dir, f"viz_{element_name}_{view_type}.html"
                )
                with open(out_path, "w", encoding="utf-8") as f:
                    f.write(html_content)
                viz_result.html_path = out_path
                saved = True
                logger.info("Saved HTML to %s", out_path)

            # Priority 3: PDF (base64-encoded binary)
            if "application/pdf" in payload and not saved:
                import base64
                pdf_b64 = payload["application/pdf"]
                out_path = os.path.join(
                    output_dir, f"viz_{element_name}_{view_type}.pdf"
                )
                with open(out_path, "wb") as f:
                    f.write(base64.b64decode(pdf_b64))
                viz_result.pdf_path = out_path
                saved = True
                logger.info("Saved PDF to %s", out_path)

            # Priority 4: PNG (base64-encoded binary)
            if "image/png" in payload and not saved:
                import base64
                png_b64 = payload["image/png"]
                out_path = os.path.join(
                    output_dir, f"viz_{element_name}_{view_type}.png"
                )
                with open(out_path, "wb") as f:
                    f.write(base64.b64decode(png_b64))
                viz_result.png_path = out_path
                saved = True
                logger.info("Saved PNG to %s", out_path)

            if saved:
                break

        # Also check stdout for any text-based diagram output (e.g., PlantUML text)
        if not saved and cell_result["stdout"]:
            stdout_text = "".join(cell_result["stdout"])
            if stdout_text.strip():
                out_path = os.path.join(
                    output_dir, f"viz_{element_name}_{view_type}.txt"
                )
                with open(out_path, "w", encoding="utf-8") as f:
                    f.write(stdout_text)
                logger.info("Saved text output to %s", out_path)
                saved = True

        if saved:
            viz_result.status = "pass"
        else:
            viz_result.status = "fail"
            viz_result.errors.append(
                "No visualization output received from %viz command. "
                "Check that the element is a package name (not a part def), "
                "and the view type is valid (tree, interconnection, Action, State)."
            )

        return viz_result


# ===========================================================================
# Notebook Generator
# ===========================================================================

class NotebookGenerator:
    """
    Generates a reviewable .ipynb notebook from validation results.
    Uses nbformat to create a notebook with the SysML kernel spec.
    """

    def __init__(self):
        try:
            import nbformat
            self.nbformat = nbformat
        except ImportError:
            raise RuntimeError(
                "nbformat is not installed. Install it with: pip install nbformat"
            )

    def _make_markdown_cell(self, source: str):
        """Create a markdown cell."""
        return self.nbformat.v4.new_markdown_cell(source=source)

    def _make_code_cell(
        self,
        source: str,
        outputs: Optional[List] = None,
    ):
        """Create a code cell with optional pre-populated outputs."""
        cell = self.nbformat.v4.new_code_cell(source=source)
        if outputs:
            # Convert plain dicts to NotebookNode objects so nbformat.write()
            # can traverse them with attribute access (e.g. output.output_type)
            from nbformat import from_dict
            cell["outputs"] = [
                from_dict(o) if isinstance(o, dict) else o
                for o in outputs
            ]
        return cell

    def _build_cell_outputs(self, file_result: FileResult) -> List[Dict]:
        """Convert a FileResult into notebook cell output objects."""
        outputs = []

        # Stdout
        for text in file_result.stdout_output:
            outputs.append({
                "output_type": "stream",
                "name": "stdout",
                "text": text,
            })

        # Warnings (stderr)
        for text in file_result.warnings:
            outputs.append({
                "output_type": "stream",
                "name": "stderr",
                "text": text,
            })

        # Errors
        if file_result.errors:
            # Separate the ename/evalue from traceback
            ename = "ValidationError"
            evalue = file_result.errors[0] if file_result.errors else ""
            traceback = file_result.errors[1:] if len(file_result.errors) > 1 else []
            outputs.append({
                "output_type": "error",
                "ename": ename,
                "evalue": evalue,
                "traceback": traceback,
            })

        # If no outputs at all, add a success indicator
        if not outputs and file_result.status == "pass":
            outputs.append({
                "output_type": "stream",
                "name": "stdout",
                "text": f"✅ {file_result.package_name} loaded successfully "
                        f"({file_result.execution_time_s}s)\n",
            })

        return outputs

    def _build_viz_outputs(self, viz_result: VizResult) -> List[Dict]:
        """Convert a VizResult into notebook cell output objects."""
        outputs = []

        if viz_result.svg_path and os.path.isfile(viz_result.svg_path):
            with open(viz_result.svg_path, "r", encoding="utf-8") as f:
                svg_content = f.read()
            outputs.append({
                "output_type": "display_data",
                "data": {"image/svg+xml": svg_content, "text/plain": f"Diagram: {viz_result.element_name}"},
                "metadata": {},
            })
        elif viz_result.html_path and os.path.isfile(viz_result.html_path):
            with open(viz_result.html_path, "r", encoding="utf-8") as f:
                html_content = f.read()
            outputs.append({
                "output_type": "display_data",
                "data": {"text/html": html_content, "text/plain": f"Diagram: {viz_result.element_name}"},
                "metadata": {},
            })
        elif viz_result.pdf_path and os.path.isfile(viz_result.pdf_path):
            import base64
            with open(viz_result.pdf_path, "rb") as f:
                pdf_b64 = base64.b64encode(f.read()).decode("ascii")
            outputs.append({
                "output_type": "display_data",
                "data": {"application/pdf": pdf_b64, "text/plain": f"Diagram (PDF): {viz_result.element_name}"},
                "metadata": {},
            })
        elif viz_result.png_path and os.path.isfile(viz_result.png_path):
            import base64
            with open(viz_result.png_path, "rb") as f:
                png_b64 = base64.b64encode(f.read()).decode("ascii")
            outputs.append({
                "output_type": "display_data",
                "data": {"image/png": png_b64, "text/plain": f"Diagram (PNG): {viz_result.element_name}"},
                "metadata": {},
            })

        if viz_result.errors:
            outputs.append({
                "output_type": "error",
                "ename": "VisualizationError",
                "evalue": viz_result.errors[0],
                "traceback": viz_result.errors[1:],
            })

        return outputs

    def generate(
        self,
        report: ValidationReport,
        output_path: str,
    ) -> str:
        """Generate the .ipynb notebook and save it to output_path."""
        nb = self.nbformat.v4.new_notebook()

        # Set kernel metadata to SysML
        nb["metadata"]["kernelspec"] = {
            "display_name": "SysML",
            "language": "sysml",
            "name": KERNEL_NAME,
        }
        nb["metadata"]["language_info"] = {
            "codemirror_mode": "sysml",
            "file_extension": ".sysml",
            "mimetype": "text/x-sysml",
            "name": "SysML",
        }

        cells = []

        # --- Title cell ---
        pass_count = report.passed
        fail_count = report.failed + report.errors
        total = report.total_files
        status_emoji = "✅" if fail_count == 0 else "⚠️"
        model_name = report.loading_order[0] if report.loading_order else "SysML v2"

        cells.append(self._make_markdown_cell(
            f"# {status_emoji} {model_name} SysML v2 Model Validation\n\n"
            f"**Generated**: {report.timestamp}  \n"
            f"**Repository**: `{report.repo_path}`  \n"
            f"**Result**: {pass_count}/{total} files passed, "
            f"{fail_count} failed  \n"
            f"**Total Time**: {report.total_time_s:.1f}s\n\n"
            f"---\n\n"
            f"Each cell below contains one `.sysml` package file, loaded "
            f"in dependency order. Re-run this notebook in JupyterLab with "
            f"the SysML kernel to reproduce the validation."
        ))

        # Group visualizations by defining package
        viz_by_pkg = defaultdict(list)
        fallback_viz_results = []
        for vr in report.viz_results:
            if getattr(vr, "package_name", None):
                viz_by_pkg[vr.package_name].append(vr)
            else:
                fallback_viz_results.append(vr)

        # --- Model loading and visualization cells ---
        cells.append(self._make_markdown_cell(
            "## Model Loading and Visualizations\n\n"
            "The following cells load each package in topological dependency "
            "order. If a package has configured visualizations, they are run "
            "immediately after the package loads."
        ))

        for file_result in report.file_results:
            # Add a small markdown comment before each cell
            status = "✅" if file_result.status == "pass" else "❌"
            rel_path = os.path.relpath(file_result.file_path, report.repo_path)

            cells.append(self._make_markdown_cell(
                f"### {status} `{file_result.package_name}` — `{rel_path}`"
            ))

            # Read the source
            source = ""
            if os.path.isfile(file_result.file_path):
                try:
                    with open(
                        file_result.file_path, "r",
                        encoding="utf-8", errors="ignore"
                    ) as f:
                        source = f.read()
                except IOError:
                    source = f"// Could not read: {file_result.file_path}"

            outputs = self._build_cell_outputs(file_result)
            cells.append(self._make_code_cell(source, outputs))

            # If there are visualizations for this package, insert them right here
            pkg_name = file_result.package_name
            if pkg_name in viz_by_pkg:
                for viz_result in viz_by_pkg[pkg_name]:
                    status_viz = "✅" if viz_result.status == "pass" else "⚠️"
                    viz_cmd = f"%viz {viz_result.element_name} --view {viz_result.view_type}"
                    cells.append(self._make_markdown_cell(
                        f"#### {status_viz} Visualization: `{viz_cmd}`"
                    ))
                    outputs_viz = self._build_viz_outputs(viz_result)
                    cells.append(self._make_code_cell(
                        viz_cmd,
                        outputs_viz,
                    ))

        # --- Fallback Visualization cells ---
        if fallback_viz_results:
            cells.append(self._make_markdown_cell(
                "## Fallback Visualizations\n\n"
                "The following cells show visualizations that could not be mapped "
                "to a specific package file."
            ))

            for viz_result in fallback_viz_results:
                status_viz = "✅" if viz_result.status == "pass" else "⚠️"
                viz_cmd = f"%viz {viz_result.element_name} --view {viz_result.view_type}"
                cells.append(self._make_markdown_cell(
                    f"### {status_viz} `{viz_cmd}`"
                ))
                outputs_viz = self._build_viz_outputs(viz_result)
                cells.append(self._make_code_cell(
                    viz_cmd,
                    outputs_viz,
                ))

        # --- Summary cell ---
        summary_rows = []
        for fr in report.file_results:
            status = "✅ Pass" if fr.status == "pass" else "❌ Fail"
            err_summary = fr.errors[0][:60] + "..." if fr.errors else "—"
            summary_rows.append(
                f"| `{fr.package_name}` | {status} | {fr.execution_time_s}s | {err_summary} |"
            )

        cells.append(self._make_markdown_cell(
            "## Summary\n\n"
            "| Package | Status | Time | Error |\n"
            "|---------|--------|------|-------|\n"
            + "\n".join(summary_rows)
        ))

        nb["cells"] = cells

        with open(output_path, "w", encoding="utf-8") as f:
            self.nbformat.write(nb, f)

        logger.info("Notebook saved to %s", output_path)
        return output_path


# ===========================================================================
# Main Orchestrator
# ===========================================================================

def find_defining_package(element_name: str, resolver: SysMLDependencyResolver) -> Optional[str]:
    """
    Find which package defines the given element by searching the package
    files or matching the package name directly.
    """
    if element_name in resolver.package_index:
        return element_name

    # Regex pattern: look for "def ElementName" or "package ElementName"
    pattern = re.compile(rf"\b(?:def|package)\s+['\"]?{re.escape(element_name)}['\"]?\b")

    for pkg_name, rel_path in resolver.package_index.items():
        abs_path = os.path.join(resolver.repo_path, rel_path)
        if os.path.isfile(abs_path):
            try:
                with open(abs_path, "r", encoding="utf-8", errors="ignore") as f:
                    content = f.read()
                if pattern.search(content):
                    return pkg_name
            except Exception:
                pass
    return None


def run_validation(
    repo_path: str,
    output_dir: str,
    viz_elements: List[Tuple[str, str]],
    timeout: int,
    dry_run: bool = False,
    continue_on_error: bool = True,
    target_package: Optional[str] = None,
) -> ValidationReport:
    """
    Main validation workflow:
    1. Resolve dependencies and determine loading order
    2. Start the SysML kernel (skipped in dry-run mode)
    3. Load each file via %publish, verify with %show, and interleave %viz
    4. Generate report and notebook
    """
    from datetime import datetime, timezone

    repo_path = os.path.abspath(repo_path)
    output_dir = os.path.abspath(output_dir)
    os.makedirs(output_dir, exist_ok=True)

    report = ValidationReport(
        timestamp=datetime.now(timezone.utc).isoformat(),
        repo_path=repo_path,
    )

    # -----------------------------------------------------------------------
    # Step 1: Resolve dependencies
    # -----------------------------------------------------------------------
    logger.info("=" * 60)
    logger.info("STEP 1: Resolving dependencies")
    logger.info("=" * 60)

    resolver = SysMLDependencyResolver(repo_path)
    loading_order = resolver.resolve()

    if target_package:
        # Check if the target is actually a file path or package name
        target_pkg_name = None
        for pkg, path in resolver.package_index.items():
            if (target_package == pkg or 
                os.path.basename(target_package) == os.path.basename(path) or 
                target_package == path or
                os.path.normpath(target_package) == os.path.normpath(path)):
                target_pkg_name = pkg
                break
        
        if not target_pkg_name:
            raise ValueError(f"Target package or file '{target_package}' not found in index.")
        
        target_package = target_pkg_name
        logger.info("Filtering dependencies for target package: %s", target_package)
        
        # Traverse dependencies recursively
        needed = set()
        queue = [target_package]
        while queue:
            curr = queue.pop(0)
            if curr not in needed:
                needed.add(curr)
                queue.extend(resolver.dep_graph.get(curr, set()))
        
        loading_order = [item for item in loading_order if item[0] in needed]
        if not loading_order:
            raise ValueError(f"No packages resolved for target '{target_package}'.")

    report.total_files = len(loading_order)
    report.loading_order = [name for name, _ in loading_order]

    logger.info("Loading order (%d files):", len(loading_order))
    for i, (name, path) in enumerate(loading_order, 1):
        logger.info("  %2d. %s", i, name)

    # Map visualization elements to their defining packages
    pkg_to_viz = defaultdict(list)
    fallback_viz = []

    if viz_elements:
        logger.info("Mapping visualization targets to defining packages...")
        for element_name, view_type in viz_elements:
            defining_pkg = find_defining_package(element_name, resolver)
            if defining_pkg:
                pkg_to_viz[defining_pkg].append((element_name, view_type))
                logger.info("  Mapped '%s:%s' to package '%s'", element_name, view_type, defining_pkg)
            else:
                fallback_viz.append((element_name, view_type))
                logger.warning("  Could not map '%s:%s' to any package (will execute as fallback)", element_name, view_type)

    # -----------------------------------------------------------------------
    # Step 2: Dry-run check
    # -----------------------------------------------------------------------
    if dry_run:
        logger.info("")
        logger.info("=" * 60)
        logger.info("DRY RUN — Skipping kernel execution")
        logger.info("=" * 60)
        logger.info("Dependency resolution succeeded. %d files would be loaded.", len(loading_order))
        for i, (name, path) in enumerate(loading_order, 1):
            rel = os.path.relpath(path, repo_path)
            logger.info("  %2d. %s  (%s)", i, name, rel)
        if viz_elements:
            viz_str = ", ".join(f"{n} --view {v}" for n, v in viz_elements)
            logger.info("Visualization targets: %s", viz_str)
        report.total_time_s = round(time.time() - time.time(), 2)
        return report

    # -----------------------------------------------------------------------
    # Step 2: Start kernel and validate
    # -----------------------------------------------------------------------
    logger.info("")
    logger.info("=" * 60)
    logger.info("STEP 2: Starting kernel and validating files")
    logger.info("=" * 60)

    validator = SysMLKernelValidator(timeout=timeout)
    overall_start = time.time()

    # Track which packages failed, so dependents can be skipped
    failed_packages: set = set()

    try:
        validator.start_kernel()

        # Load each file in dependency order
        for i, (pkg_name, file_path) in enumerate(loading_order, 1):
            rel_path = os.path.relpath(file_path, repo_path)

            # Check if any dependency of this package failed
            if continue_on_error:
                pkg_deps = resolver.dep_graph.get(pkg_name, set())
                failed_deps = pkg_deps & failed_packages
                if failed_deps:
                    logger.warning(
                        "[%d/%d] SKIPPING %s — depends on failed: %s",
                        i, len(loading_order), pkg_name,
                        ", ".join(sorted(failed_deps)),
                    )
                    skip_result = FileResult(
                        package_name=pkg_name,
                        file_path=file_path,
                        status="skipped",
                        errors=[f"Skipped: dependency failed ({', '.join(sorted(failed_deps))})"],
                    )
                    report.file_results.append(skip_result)
                    report.skipped += 1
                    failed_packages.add(pkg_name)
                    continue

            logger.info(
                "[%d/%d] Loading %s (%s)...",
                i, len(loading_order), pkg_name, rel_path,
            )

            file_result = validator.validate_file(pkg_name, file_path)
            report.file_results.append(file_result)

            if file_result.status == "pass":
                report.passed += 1
                method_info = f" via %{file_result.load_method}" if file_result.load_method else ""
                logger.info(
                    "  ✅ OK (%.1fs%s)", file_result.execution_time_s, method_info
                )

                # Interleaved visualization: run %viz commands for this package immediately!
                if pkg_name in pkg_to_viz:
                    for element_name, view_type in pkg_to_viz[pkg_name]:
                        viz_result = validator.run_viz(element_name, output_dir, view_type)
                        viz_result.package_name = pkg_name
                        report.viz_results.append(viz_result)

                        if viz_result.status == "pass":
                            saved_to = (
                                viz_result.svg_path or viz_result.html_path
                                or viz_result.pdf_path or viz_result.png_path
                            )
                            logger.info("  ✅ Viz: %s (%s) → %s", element_name, view_type, saved_to)
                        else:
                            for err in viz_result.errors:
                                logger.warning("  ⚠️ Viz: %s (%s): %s", element_name, view_type, err)
            else:
                report.failed += 1
                failed_packages.add(pkg_name)
                for err in file_result.errors:
                    logger.error("  ❌ %s", err)

                if not continue_on_error:
                    logger.error(
                        "Stopping: --no-continue-on-error is set and %s failed.",
                        pkg_name,
                    )
                    break

        # -------------------------------------------------------------------
        # Step 3: Fallback/Remaining Visualizations
        # -------------------------------------------------------------------
        if fallback_viz:
            logger.info("")
            logger.info("=" * 60)
            logger.info("STEP 3: Generating fallback visualizations")
            logger.info("=" * 60)

            for element_name, view_type in fallback_viz:
                viz_result = validator.run_viz(element_name, output_dir, view_type)
                viz_result.package_name = None
                report.viz_results.append(viz_result)

                if viz_result.status == "pass":
                    saved_to = (
                        viz_result.svg_path or viz_result.html_path
                        or viz_result.pdf_path or viz_result.png_path
                    )
                    logger.info("  ✅ Fallback Viz: %s (%s) → %s", element_name, view_type, saved_to)
                else:
                    for err in viz_result.errors:
                        logger.warning("  ⚠️ Fallback Viz: %s (%s): %s", element_name, view_type, err)

    except RuntimeError as e:
        logger.error("Kernel error: %s", e)
        report.errors += 1
    finally:
        validator.shutdown_kernel()


    report.total_time_s = round(time.time() - overall_start, 2)

    # -----------------------------------------------------------------------
    # Step 4: Generate outputs
    # -----------------------------------------------------------------------
    logger.info("")
    logger.info("=" * 60)
    logger.info("STEP 4: Generating outputs")
    logger.info("=" * 60)

    # JSON report
    json_path = os.path.join(output_dir, "validation_report.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(asdict(report), f, indent=2, default=str)
    logger.info("JSON report saved to %s", json_path)

    # Notebook
    try:
        nb_gen = NotebookGenerator()
        first_pkg = report.loading_order[0].lower() if report.loading_order else "validation"
        nb_name = f"{first_pkg}_validation.ipynb"
        nb_path = os.path.join(output_dir, nb_name)
        nb_gen.generate(report, nb_path)
    except RuntimeError as e:
        logger.error("Could not generate notebook: %s", e)
        nb_path = None

    # -----------------------------------------------------------------------
    # Final summary
    # -----------------------------------------------------------------------
    logger.info("")
    logger.info("=" * 60)
    logger.info("VALIDATION COMPLETE")
    logger.info("=" * 60)
    logger.info(
        "  Files: %d total, %d passed, %d failed, %d skipped",
        report.total_files, report.passed, report.failed, report.skipped,
    )
    logger.info("  Time:  %.1fs", report.total_time_s)
    logger.info("  Outputs:")
    logger.info("    - %s", json_path)
    if nb_path and os.path.isfile(nb_path):
        logger.info(
            "    - %s",
            nb_path,
        )
    for vr in report.viz_results:
        for path in (vr.svg_path, vr.html_path, vr.pdf_path, vr.png_path):
            if path:
                logger.info("    - %s", path)

    return report


# ===========================================================================
# CLI
# ===========================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Validate a SysML v2 model using the Jupyter kernel.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python scripts/validate_model.py\n"
            "  python scripts/validate_model.py --verbose\n"
            "  python scripts/validate_model.py --viz-elements SaturnV,Apollo11Mission\n"
            "  python scripts/validate_model.py --repo-path . --output-dir scripts/output\n"
        ),
    )

    # Auto-detect repo path: script is in scripts/, repo is parent
    default_repo = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "..")
    )
    default_output = os.path.join(
        os.path.dirname(__file__), "output"
    )

    parser.add_argument(
        "--repo-path",
        default=default_repo,
        help=f"Path to the SysML v2 repository root (default: {default_repo})",
    )
    parser.add_argument(
        "--output-dir",
        default=default_output,
        help=f"Output directory for report, notebook, and diagrams (default: {default_output})",
    )
    # Format default viz for display
    default_viz_str = ",".join(
        f"{name}:{view}" for name, view in DEFAULT_VIZ_ELEMENTS
    )

    parser.add_argument(
        "--viz-elements",
        default=default_viz_str,
        help=(
            "Comma-separated list of element:view pairs to visualize with %%viz. "
            "Format: 'ElementName:ViewType' (e.g., 'SaturnV:tree,ApolloSpacecraft:interconnection'). "
            "If no ':ViewType' is given, the --viz-view default is used. "
            f"(default: {default_viz_str})"
        ),
    )
    parser.add_argument(
        "--viz-view",
        default="tree",
        help="Default view type for %%viz when not specified per-element (default: tree)",
    )
    parser.add_argument(
        "--no-viz",
        action="store_true",
        help="Skip visualization step entirely",
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=60,
        help="Per-cell execution timeout in seconds (default: 60)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Resolve dependencies and print loading order without starting the kernel",
    )
    parser.add_argument(
        "--no-continue-on-error",
        action="store_true",
        help="Stop immediately when a file fails (default: continue and skip dependents)",
    )
    parser.add_argument(
        "--target-package",
        default=None,
        help="Specific package name or file path to validate. Only this and its dependencies will be loaded.",
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Enable debug-level logging",
    )

    args = parser.parse_args()

    # Configure logging
    log_level = logging.DEBUG if args.verbose else logging.INFO
    logging.basicConfig(
        level=log_level,
        format="%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%H:%M:%S",
    )

    # Parse viz elements: support "Element:View" or just "Element" (uses --viz-view default)
    viz_elements = []
    if not args.no_viz:
        for entry in args.viz_elements.split(","):
            entry = entry.strip()
            if not entry:
                continue
            if ":" in entry:
                name, view = entry.split(":", 1)
                viz_elements.append((name.strip(), view.strip()))
            else:
                viz_elements.append((entry, args.viz_view))

    # Run validation
    report = run_validation(
        repo_path=args.repo_path,
        output_dir=args.output_dir,
        viz_elements=viz_elements,
        timeout=args.timeout,
        dry_run=args.dry_run,
        continue_on_error=not args.no_continue_on_error,
        target_package=args.target_package,
    )

    # Exit with non-zero code if any files failed
    if report.failed > 0 or report.errors > 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
